default_platform(:ios)

platform :ios do
  desc "Build unsigned Release archive and package IPA"
  lane :build_unsigned do
    gym(
      project: "PureReader.xcodeproj",
      scheme: "PureReader",
      configuration: "Release",
      clean: true,
      skip_codesigning: true,
      export_method: "development",
      output_directory: "./build/ipa",
      output_name: "PureReader-unsigned",
      destination: "generic/platform=iOS",
      xcargs: "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' DEVELOPMENT_TEAM=''"
    )
  end
end
